[versions]
picortex = "0.0.93"
authenticator = "0.0.06"
bitframe = "0.10.55"
server-ip = "65.21.254.230"
server-user = "root"
server-password = "bitframe"

[libraries]
authenticator-api-core = { module = "com.picortex:authenticator-api-core", version.ref = "authenticator" }
authenticator-api-ktor = { module = "com.picortex:authenticator-api-ktor", version.ref = "authenticator" }
authenticator-api-mock = { module = "com.picortex:authenticator-api-mock", version.ref = "authenticator" }

authenticator-sdk-client-core = { module = "com.picortex:authenticator-sdk-client-core", version.ref = "authenticator" }

bitframe-actor-user = { module = "com.picortex:bitframe-actor-user", version.ref = "bitframe" }
bitframe-actor-space = { module = "com.picortex:bitframe-actor-space", version.ref = "bitframe" }

bitframe-api-core = { module = "com.picortex:bitframe-api-core", version.ref = "bitframe" }
bitframe-api-ktor = { module = "com.picortex:bitframe-api-ktor", version.ref = "bitframe" }
bitframe-api-mock = { module = "com.picortex:bitframe-api-mock", version.ref = "bitframe" }

bitframe-authentication-core = { module = "com.picortex:bitframe-authentication-core", version.ref = "bitframe" }
bitframe-authentication-daod = { module = "com.picortex:bitframe-authentication-daod", version.ref = "bitframe" }

bitframe-dao-mock = { module = "com.picortex:bitframe-dao-mock", version.ref = "bitframe" }
bitframe-dao-mongo = { module = "com.picortex:bitframe-dao-mongo", version.ref = "bitframe" }
bitframe-dao = { module = "com.picortex:bitframe-dao", version.ref = "bitframe" }

bitframe-sdk-client-core = { module = "com.picortex:bitframe-sdk-client-core", version.ref = "bitframe" }
bitframe-sdk-client-mock = { module = "com.picortex:bitframe-sdk-client-mock", version.ref = "bitframe" }

bitframe-sdk-server-core = { module = "com.picortex:bitframe-sdk-server-core", version.ref = "bitframe" }
bitframe-sdk-server-ktor = { module = "com.picortex:bitframe-sdk-server-ktor", version.ref = "bitframe" }
bitframe-sdk-server-test = { module = "com.picortex:bitframe-sdk-server-test", version.ref = "bitframe" }

bitframe-service-builder-rest = { module = "com.picortex:bitframe-service-builder-rest", version.ref = "bitframe" }

bitframe-service-builder-api-core = { module = "com.picortex:bitframe-service-builder-api-core", version.ref = "bitframe" }
bitframe-service-builder-api-ktor = { module = "com.picortex:bitframe-service-builder-api-ktor", version.ref = "bitframe" }
bitframe-service-builder-api-mock = { module = "com.picortex:bitframe-service-builder-api-mock", version.ref = "bitframe" }

bitframe-service-builder-core = { module = "com.picortex:bitframe-service-builder-core", version.ref = "bitframe" }
bitframe-service-builder-daod = { module = "com.picortex:bitframe-service-builder-daod", version.ref = "bitframe" }

bitframe-service-builder-sdk-client-core = { module = "com.picortex:bitframe-service-builder-sdk-client-core", version.ref = "bitframe" }
bitframe-service-builder-sdk-client-react = { module = "com.picortex:bitframe-service-builder-sdk-client-react", version.ref = "bitframe" }

bitframe-service-builder-sdk-server-core = { module = "com.picortex:bitframe-service-builder-sdk-server-core", version.ref = "bitframe" }

datetime-core = { module = "com.picortex:datetime-core", version.ref = "bitframe" }

events-react = { module = "com.picortex:events-react", version.ref = "bitframe" }
presenters-core = { module = "com.picortex:presenters-core", version.ref = "bitframe" }
presenters-mock = { module = "com.picortex:presenters-mock", version.ref = "bitframe" }

mailer-smtp = { module = "com.picortex:mailer-smtp", version.ref = "bitframe" }

response = { module = "com.picortex:response", version.ref = "bitframe" }

validation = { module = "com.picortex:validation", version.ref = "bitframe" }

[plugins]
root-docker-compose = { id = "docker-compose", version.ref = "bitframe" }
docker-compose = { id = "docker-compose" }

root-publish = { id = "picortex-publish", version.ref = "bitframe" }
publish = { id = "picortex-publish" }
